'use client'
import {NextUIProvider} from '@nextui-org/react'
import './globals.css'
import {Inter} from 'next/font/google'
import React from "react";
import Head from "next/head";

const inter = Inter({subsets: ['latin']})

// export const metadata: Metadata = {
//     title: 'Shri Krishna Commercials',
//     description: 'Generated by create next app',
//
// }

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {

    return (
        <html lang="en">
        <Head>
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link rel="preconnect" href="https://fonts.gstatic.com"/>
            <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;400;700;900&display=swap"
                  rel="stylesheet"/>

            <link
                rel="stylesheet"
                type="text/css"
                href="/font-awesome-4.7.0/css/font-awesome.min.css"
            />
        </Head>


        <body className={inter.className}>

        <div className="icon-bar hidden sm:block">
            <a href="mailto:info@skcommercial.in" className="email">

                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path fillRule="evenodd" clipRule="evenodd"
                          d="M3.00977 5.83789C3.00977 5.28561 3.45748 4.83789 4.00977 4.83789H20C20.5523 4.83789 21 5.28561 21 5.83789V17.1621C21 18.2667 20.1046 19.1621 19 19.1621H5C3.89543 19.1621 3 18.2667 3 17.1621V6.16211C3 6.11449 3.00333 6.06765 3.00977 6.0218V5.83789ZM5 8.06165V17.1621H19V8.06199L14.1215 12.9405C12.9499 14.1121 11.0504 14.1121 9.87885 12.9405L5 8.06165ZM6.57232 6.80554H17.428L12.7073 11.5263C12.3168 11.9168 11.6836 11.9168 11.2931 11.5263L6.57232 6.80554Z"
                          fill="currentColor"/>
                </svg>
            </a>

            <a href="https://www.facebook.com/profile.php?id=100082803202459" className="facebook">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M9.19795 21.5H13.198V13.4901H16.8021L17.198 9.50977H13.198V7.5C13.198 6.94772 13.6457 6.5 14.198 6.5H17.198V2.5H14.198C11.4365 2.5 9.19795 4.73858 9.19795 7.5V9.50977H7.19795L6.80206 13.4901H9.19795V21.5Z"
                        fill="currentColor"/>
                </svg>

            </a>

            <a href="https://www.linkedin.com/company/89841311/admin/" className="linkedin">
                L

            </a>
            <a href="https://www.instagram.com/shri_krishna_commercial_/ " className="instagram">

                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path fillRule="evenodd" clipRule="evenodd"
                          d="M12 7C9.23858 7 7 9.23858 7 12C7 14.7614 9.23858 17 12 17C14.7614 17 17 14.7614 17 12C17 9.23858 14.7614 7 12 7ZM9 12C9 13.6569 10.3431 15 12 15C13.6569 15 15 13.6569 15 12C15 10.3431 13.6569 9 12 9C10.3431 9 9 10.3431 9 12Z"
                          fill="currentColor"/>
                    <path
                        d="M18 5C17.4477 5 17 5.44772 17 6C17 6.55228 17.4477 7 18 7C18.5523 7 19 6.55228 19 6C19 5.44772 18.5523 5 18 5Z"
                        fill="currentColor"/>
                    <path fillRule="evenodd" clipRule="evenodd"
                          d="M5 1C2.79086 1 1 2.79086 1 5V19C1 21.2091 2.79086 23 5 23H19C21.2091 23 23 21.2091 23 19V5C23 2.79086 21.2091 1 19 1H5ZM19 3H5C3.89543 3 3 3.89543 3 5V19C3 20.1046 3.89543 21 5 21H19C20.1046 21 21 20.1046 21 19V5C21 3.89543 20.1046 3 19 3Z"
                          fill="currentColor"/>
                </svg>

            </a>

        </div>

        <NextUIProvider>
            {children}
        </NextUIProvider>
        </body>
        </html>
    )
}
